spring:
    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:mem:ssubob
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        defer-datasource-initialization: false
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
    profiles:
        active: api